### ISSUE TITLE
The app crashes because it cannot create the viewmodel instance 

### ISSUE THREAD

**Issue by WasimReza2K8** [googlecodelabs/android-room-with-a-view#145]
After running the code I got the following error message from android studio. Basically, it cannot create the viewmodel because it has a dependency on the application reference. However, the initialization did not mention from where the viewmodel collects the dependency.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.roomwordssample/com.example.android.roomwordssample.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.android.roomwordssample.WordViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.android.roomwordssample.WordViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.example.android.roomwordssample.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.example.android.roomwordssample.WordViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)

**Comment by florina-muntenescu** [comment]
Which version of the codelab is this, Java or Kotlin?

**Comment by Akiva-Grobman** [comment]
I had the same problem(in java). This solved it:
new ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory.getInstance(getApplication())).get(WordViewModel.class);

**Comment by WasimReza2K8** [comment]
It is in java version.

Best regards
Wasim

**Comment by Akiva-Grobman** [comment]
Check out my previous comment and see if it help.

**Comment by hansRapnhap** [comment]
Akiva's solution helps. Why do you not include that in the note and in the 
https://developer.android.com/codelabs/android-room-with-a-view
pages?
I followed the complete course, and ended in loosing time by this not working code part !

**Comment by Akiva-Grobman** [comment]
Give them some time, I'm sure it will be fixed.

**Comment by flypadre** [comment]
For anyone who doesn't know the line of code can be found in MainActivity.java

**Comment by KJH1964** [comment]
Thanks, I'd figured out it was in that line of code, just didn't know what to do about it. I'd tracked down the exception being thrown in the ActivityThread.java class when that line was executed. But it would have taken me a long time to get from there to the change above. As hansRapnhap says it would be nice if they updated GitHub.

**Comment by Akiva-Grobman** [comment]
> Thanks, I'd figured out it was in that line of code, just didn't know what to do about it. I'd tracked down the exception being thrown in the ActivityThread.java class when that line was executed. But it would have taken me a long time to get from there to the change above. As hansRapnhap says it would be nice if they updated GitHub. Still I learnt some more about tracking down bugs, even if I didn't fix it.

I've made a PR but it doesn't pass a firebase test so they didn't except it.

**Comment by SharifMrCreed** [comment]
> I had the same problem(in java). This solved it:
> // old code
> mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
> // new code
> mWordViewModel = new ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory.getInstance(getApplication())).get(WordViewModel.class);

Man thanx alot for this been at it for almost 2 days to thing it would be solved so simply like this.

**Comment by fanysoft** [comment]
fix : 
1] change public class WordViewModel extends ViewModel  (not AndroidViewModel)
2] add method to WordViewModel
public void init(Application application){
        mRepository = new WordRepository(application);
        mAllWords = mRepository.getAllWords();
    }
3) add to MainActivity
  mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
        mWordViewModel.init(this.getApplication());

**Comment by Ecliip** [comment]
> I had the same problem(in java). This solved it:
> // old code
> mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
> // new code
> mWordViewModel = new ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory.getInstance(getApplication())).get(WordViewModel.class);

Your solution works just fine.
Original github version is not fixed yet

**Comment by shiyinghan** [comment]
New version of 'androidx.appcompat' dependencies can fix this problem:
// old code
ext {
    appCompatVersion = '1.2.0'
    ...
}
// new code
ext {
    appCompatVersion = '1.3.0-rc01'
    ...
}

**Comment by kitaret1** [comment]
> New version of 'androidx.appcompat' dependencies can fix this problem:
> // old code
> ext {
> appCompatVersion = '1.2.0'
> ...
> }
> // new code
> ext {
> appCompatVersion = '1.3.0-rc01'
> ...
> }

This is the best solution, and remember to extend AndroidViewModelel instead of ViewModel,
Works in fragment like this
MyViewmodel = new ViewModelProvider(require activity()).get(MyViewModel.class);

**Comment by SunitRoy2703** [comment]
> fix :
> 1] change public class WordViewModel extends ViewModel (not AndroidViewModel)
> 2] add method to WordViewModel
> public void init(Application application){
> mRepository = new WordRepository(application);
> mAllWords = mRepository.getAllWords();
> }
> 3) add to MainActivity
> mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
> mWordViewModel.init(this.getApplication());
> 
> so sad even Googles own demos are crashing .. we are all humans only :]

If anyone is facing the same problem, like I was
You can try this, it works!

**Comment by surajsahani** [comment]
> I had the same problem(in java). This solved it:
> // old code
> mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
> // new code
> mWordViewModel = new ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory.getInstance(getApplication())).get(WordViewModel.class);

fucking ninja, work like a charm

**Comment by florina-muntenescu** [comment]
Version bumps should have fixed this in both [Java](#182 ) and [Kotlin](#181 ) versions of the codelab

**Comment by Codzure** [comment]
[Kotlin] `private val vm: HomeViewModel by viewModels()` I faced the issue but resolved by annotating Hilt on my Activity @AndroidEntryPoint

**Comment by quyle1222** [comment]
> 
In Fragmet like:
mWordViewModel = new ViewModelProvider (this, ViewModelProvider.AndroidViewModelFactory.getInstance (this.getActivity().getApplication())). get (WordViewModel.class);

**Comment by Sudeep152** [comment]
This is not working for me 

        authViewModel =
            ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory.getInstance(
                this.activity!!.application)).get(
                Student_Auth_ViewModel::class.java)

**Comment by Jayjerome** [comment]
Still having this issue on Kotlin. I've add `@AndroidEntryPoint` in my activity but still same error. How did you guys resolve this for Kotlin?

**Comment by surajsahani** [comment]
> Still having this issue on Kotlin. I've add `@AndroidEntryPoint` in my activity but still same error. How did you guys resolve this for Kotlin?

looks like issue of Dagger. can you sent entire trace here. thanks

**Comment by Jayjerome** [comment]
Here's the error trace 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.edekee.edekee, PID: 31937
    java.lang.RuntimeException: Cannot create an instance of class com.edekee.product.viewModel.ProductViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.edekee.product.fragments.UploadProductsFragment.onCreateView(UploadProductsFragment.kt:71)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.InstantiationException: java.lang.Class<com.edekee.product.viewModel.ProductViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.edekee.product.fragments.UploadProductsFragment.onCreateView(UploadProductsFragment.kt:71) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:264) 
        at android.app.ActivityThread.main(ActivityThread.java:7684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
I/Process: Sending signal. PID: 31937 SIG: 9`

**Comment by Jayjerome** [comment]
Then my view model class 


`@HiltViewModel
class ProductViewModel
@Inject
constructor(private val repository: ImageRepository) : ViewModel() {
    
    val allImages: LiveData<List<Image>> = repository.allImages.asLiveData()

    fun insert(image: Image) = viewModelScope.launch {
        repository.insert(image)
    }
}

class ImageViewModelFactory(private val repository: ImageRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(ProductViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return ProductViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
`

@surajsahani

**Comment by nemamayank** [comment]
**Hello guys can you help me out** 

_Below is my trace and reported in play store as well_

```
java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4035)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4201)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2438)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by: androidx.fragment.app.Fragment$InstantiationException:
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:628)
  at androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:483)
  at androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:85)
  at androidx.fragment.app.FragmentManager.restoreSaveState (FragmentManager.java:2728)
  at androidx.fragment.app.FragmentController.restoreSaveState (FragmentController.java:198)
  at androidx.fragment.app.FragmentActivity$2.onContextAvailable (FragmentActivity.java:149)
  at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.java:99)
  at androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:313)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:273)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java:115)
  at dagger.android.support.DaggerAppCompatActivity.onCreate (DaggerAppCompatActivity.java:53)
  at nl.ockto.mobile.presentation.ui.common.BaseActivity.onCreate (BaseActivity.kt:20)
  at nl.ockto.mobile.presentation.ui.main.MainActivity.onCreate (MainActivity.kt:142)
  at android.app.Activity.performCreate (Activity.java:8290)
  at android.app.Activity.performCreate (Activity.java:8270)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4009)
Caused by: java.lang.NoSuchMethodException:
  at java.lang.Class.getConstructor0 (Class.java:2363)
  at java.lang.Class.getConstructor (Class.java:1759)
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:613)
```
Code Snip:
`if (viewModelClass != null)
            _viewModel = ViewModelProvider(this, viewModelProviderFactory).get(viewModelClass)`

**Comment by morarafrank** [comment]
Use @AndroidEntryPoint annotation on your main activity if you are using Dagger or Hilt for DI.

**Comment by elvissalabarria** [comment]
I used @androidentrypoint but i have the same error

**Comment by morarafrank** [comment]
> I used @androidentrypoint but i have the same error

If you're using Hilt for DI, is your ViewModel class annotated with @HiltViewModel. I faced the same issue and solved it after annotating my ViewModel with @HiltViewModel.

**Comment by clerdson** [comment]
ok implements dependency manually and ViewModel crash when pass params 
for this dependency injection

**Comment by clerdson** [comment]
val loginViewModel: LoginViewModel by viewModels<LoginViewModel> { LoginViewModel.Factory }

**Comment by clerdson** [comment]
https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-factories?hl=pt-br

**Comment by shagunshota** [comment]
I am getting a error  how to resolve it nothing is working
FATAL EXCEPTION: main
  Process: com.example.crudoperation, PID: 16087     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.crudoperation/com.example.crudoperation.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.crudoperation.NoteViewModel
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3675)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                                                                                    Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.crudoperation.NoteViewModel
                                                                                                    	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:204)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at com.example.crudoperation.MainActivity.onCreate(MainActivity.kt:22)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8050)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8030)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3648)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
                                                                                                    Caused by: java.lang.NoSuchMethodException: com.example.crudoperation.NoteViewModel.<init> []
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2363)
                                                                                                    	at java.lang.Class.getDeclaredConstructor(Class.java:2201)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:202)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153) 
                                                                                                    	at com.example.crudoperation.MainActivity.onCreate(MainActivity.kt:22) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8050) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8030) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3648) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
